# Generated by Selenium IDE
from selenium.webdriver.common.by import By


class TestDownloaddatasets:
    def test_downloaddatasets(self, driver):
        driver.get("http://127.0.0.1:5000/")
        driver.set_window_size(913, 1068)
        driver.find_element(By.CSS_SELECTOR, ".card:nth-child(1) .d-flex a").click()
        driver.find_element(By.CSS_SELECTOR, ".mt-2").click()
        driver.find_element(By.LINK_TEXT, "2").click()
        driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
