# Generated by Selenium IDE
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait


class TestAddremovedatasetstocart:
    def test_addremovedatasetstocart(self, driver):
        driver.get("http://127.0.0.1:5000/")
        driver.set_window_size(1000, 1093)
        WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.LINK_TEXT, "Login"))).click()
        driver.find_element(By.ID, "email").click()
        driver.find_element(By.ID, "email").send_keys("user1@example.com")
        driver.find_element(By.ID, "password").send_keys("1234")
        driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
        WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".card:nth-child(1) .d-flex a")))
        first_card = driver.find_element(By.CSS_SELECTOR, ".card:nth-child(1) .d-flex a")
        first_card.click()
        driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(2) .btn-outline-success").click()
        driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(3) .btn-outline-success").click()
        driver.get("http://127.0.0.1:5000/")
        WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".card:nth-child(1) .d-flex a")))
        driver.find_element(By.CSS_SELECTOR, ".card:nth-child(1) .d-flex a").click()
        driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(3) .btn-outline-success").click()
        driver.find_element(By.CSS_SELECTOR, ".nav-link > .feather").click()
        WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".cart-item .btn-outline-danger")))
        driver.find_element(By.CSS_SELECTOR, ".cart-item .btn-outline-danger").click()
        assert driver.switch_to.alert.text == "Remove this model from your cart?"
        driver.switch_to.alert.accept()
        WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".btn-outline-secondary")))
        driver.find_element(By.CSS_SELECTOR, ".btn-outline-secondary").click()
        assert driver.switch_to.alert.text == "Are you sure you want to remove all items from your cart?"
        driver.switch_to.alert.accept()
