# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestDownloaddatasets:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_downloaddatasets(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(902, 1068)
        self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(1) .d-flex a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".mt-2").click()
        self.driver.find_element(By.LINK_TEXT, "2").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
