# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestDownloaddifferentdatasets:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_downloaddifferentdatasets(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(913, 1068)
        self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(1) .d-flex a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".mt-2").click()
        self.driver.find_element(By.CSS_SELECTOR, ".hamburger").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(2) .align-middle:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(3) .d-flex a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".mt-2").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav-link > .feather").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
