# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys


class TestAddremovedatasetstocart:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_addremovedatasetstocart(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(1000, 1093)
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
        self.driver.find_element(By.ID, "password").send_keys("1234")
        self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
        self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(1) .d-flex a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(2) .btn-outline-success").click()
        self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(3) .btn-outline-success").click()
        self.driver.find_element(By.LINK_TEXT, "SongHub Sample Pack Vol. 1").click()
        self.driver.find_element(By.CSS_SELECTOR, ".mt-2").click()
        self.driver.find_element(By.LINK_TEXT, "Sample dataset 3").click()
        self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(3) .btn-outline-success").click()
        self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(1) .d-flex a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".mt-2").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav-link > .feather").click()
        self.driver.find_element(By.CSS_SELECTOR, "#cart-item-15 .btn").click()
        assert self.driver.switch_to.alert.text == "Remove this model from your cart?"
        self.driver.switch_to.alert.accept()
        self.driver.find_element(By.CSS_SELECTOR, "#cart-item-14 .btn").click()
        assert self.driver.switch_to.alert.text == "Remove this model from your cart?"
        self.driver.switch_to.alert.accept()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-secondary").click()
        assert self.driver.switch_to.alert.text == "Are you sure you want to remove all items from your cart?"
        self.driver.switch_to.alert.accept()
