# Generated by Selenium IDE
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait


class TestDownloaddifferentdatasets:
    def test_downloaddifferentdatasets(self, driver):
        driver.get("http://127.0.0.1:5000/")
        driver.set_window_size(913, 1068)
        driver.find_element(By.CSS_SELECTOR, ".card:nth-child(1) .d-flex a").click()
        driver.find_element(By.CSS_SELECTOR, ".mt-2").click()
        driver.find_element(By.CSS_SELECTOR, ".hamburger").click()
        WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, ".sidebar-item:nth-child(2) .align-middle:nth-child(2)"))
        ).click()
        driver.find_element(By.CSS_SELECTOR, ".card:nth-child(3) .d-flex a").click()
        driver.find_element(By.CSS_SELECTOR, ".mt-2").click()
        driver.find_element(By.CSS_SELECTOR, ".nav-link > .feather").click()
        driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
