"""empty message

Revision ID: b0d7c85929c4
Revises: bc5d7828ed7f
Create Date: 2025-12-13 11:53:45.776726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0d7c85929c4'
down_revision = 'bc5d7828ed7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uvl_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['data_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("UPDATE data_set SET dataset_type = 'uvl_dataset'")
    op.execute("DELETE FROM uvl_dataset")
    op.execute("INSERT INTO uvl_dataset (id) SELECT id FROM data_set")

    op.drop_table('webhook')
    # with op.batch_alter_table('user_session', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idx_user_sessions'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_sessions'), ['user_id', 'last_activity'], unique=False)

    op.create_table('webhook',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('uvl_dataset')
    # ### end Alembic commands ###
