"""empty message

Revision ID: c3982b56aec0
Revises: b0d7c85929c4
Create Date: 2025-12-13 12:50:58.974345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3982b56aec0'
down_revision = 'b0d7c85929c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_meta_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('publication_type', sa.Enum('NONE', 'ANNOTATION_COLLECTION', 'BOOK', 'BOOK_SECTION', 'CONFERENCE_PAPER', 'DATA_MANAGEMENT_PLAN', 'JOURNAL_ARTICLE', 'PATENT', 'PREPRINT', 'PROJECT_DELIVERABLE', 'PROJECT_MILESTONE', 'PROPOSAL', 'REPORT', 'SOFTWARE_DOCUMENTATION', 'TAXONOMIC_TREATMENT', 'TECHNICAL_NOTE', 'THESIS', 'WORKING_PAPER', 'OTHER', name='publicationtype'), nullable=False),
    sa.Column('publication_doi', sa.String(length=120), nullable=True),
    sa.Column('tags', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_set_id', sa.Integer(), nullable=False),
    sa.Column('audio_meta_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audio_meta_data_id'], ['audio_meta_data.id'], ),
    sa.ForeignKeyConstraint(['data_set_id'], ['data_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['data_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_meta_data_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'audio_meta_data', ['audio_meta_data_id'], ['id'])

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'audio', ['audio_id'], ['id'])

    # with op.batch_alter_table('user_session', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idx_user_sessions'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('user_session', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('idx_user_sessions'), ['user_id', 'last_activity'], unique=False)

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('audio_id')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('audio_meta_data_id')

    op.drop_table('audio_dataset')
    op.drop_table('audio')
    op.drop_table('audio_meta_data')
    # ### end Alembic commands ###
