"""refactor_to_polymorphic

Revision ID: cd40fbad41c4
Revises: 004
Create Date: 2025-12-08 21:15:40.198654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd40fbad41c4'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataset_type', sa.String(length=50), nullable=True))

    # Data migration: Assume all existing datasets are UVL
    op.execute("UPDATE data_set SET dataset_type = 'dataset' WHERE dataset_type IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_sessions'), ['user_id', 'last_activity'], unique=False)

    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_column('dataset_type')

    op.drop_table('uvl_dataset')
    # ### end Alembic commands ###
